openapi: 3.0.1
info:
  title: "Orders API"
  version: "1.0.0"
  description: "Esta API proporciona operaciones CRUD para gestionar órdenes."
paths:
  /api/orders:
    get:
      summary: Obtener órdenes
      description: Retorna una lista de órdenes
      responses:
        '200':
          description: Lista de órdenes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '401':
          description: No autorizado
        '403':
          description: Prohibido
    post:
      summary: Crear nueva orden
      description: Crea una nueva orden
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Orden creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '401':
          description: No autorizado
        '403':
          description: Prohibido
  /api/orders/{id}:
    put:
      summary: Actualizar orden
      description: Actualiza una orden existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de la orden a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Orden actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: No autorizado
        '403':
          description: Prohibido
        '404':
          description: Orden no encontrada
    delete:
      summary: Eliminar orden
      description: Elimina una orden existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de la orden a eliminar
      responses:
        '204':
          description: Orden eliminada exitosamente
        '401':
          description: No autorizado
        '403':
          description: Prohibido
        '404':
          description: Orden no encontrada
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        productId:
          type: integer
          format: int64
          example: 101
        unitPrice:
          type: number
          format: double
          example: 49.99
        quantity:
          type: integer
          example: 2
        total:
          type: number
          format: double
          example: 99.98
        date:
          type: string
          format: date
          example: "2023-06-28"
        notes:
          type: string
          example: "Notas sobre la orden"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
